build.sh: Do away with custom Python
Apart from taking quite a while to build and being horrifically insecure (by accident, we found out that we could have been executing arbitary Python code downloaded via HTTP from a spammer - see #https://github.com/liqd/adhocracy/pull/968) - the custom Python version does not build anymore, despite numerous bugfixes.

Even after fixing our code, collective.recipe.cmmi 0.5 cannot be built these days because of missing dependencies.

ALso, the very error message is broken:

    Got collective.recipe.cmmi 0.5.
    While:
    Installing.
    Getting section readline.
    Initializing section readline.
    Installing recipe collective.recipe.cmmi.

    An internal error occured due to a bug in either zc.buildout or in a
    recipe being used:
    Traceback (most recent call last):
    File "/home/phihag/adhocracy_buildout/python/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 1683, in main
        getattr(buildout, command)(args)
    File "/home/phihag/adhocracy_buildout/python/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 439, in install
        [self[part]['recipe'] for part in install_parts]
    File "/home/phihag/adhocracy_buildout/python/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 987, in __getitem__
        options._initialize()
    File "/home/phihag/adhocracy_buildout/python/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 1071, in _initialize
        recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
    File "/home/phihag/adhocracy_buildout/python/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 1027, in _install_and_load
        allow_hosts=buildout._allow_hosts
    File "/home/phihag/adhocracy_buildout/python/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/easy_install.py", line 800, in install
        return installer.install(specs, working_set)
    File "/home/phihag/adhocracy_buildout/python/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/easy_install.py", line 662, in install
        [requirement] = err
    ValueError: too many values to unpack

Therefore, simply install PIL instead of a custom Python build.