fix thumbnail badge size
the old version gave

  TypeError: cannot concatenate 'str' and 'int' objects

when only one of thumbnail height and width was set on the
instance level.